### ISSUE TITLE
Improve Markdown output for enum expansion

### ISSUE THREAD

**Issue by atmamont** [Adyen/adyen-swift-public-api-diff#69]
# Summary 
Here is an partial example of enum change when one enum case is being expanded. New enum cases are not displayed as they usually go into the "Added" section.

```swift
// From
case boleto

// To
@available(*, deprecated, renamed: "boletoBancarioSantander", message: "Use 'boletoBancarioSantander' instead. Consider 'boletoBancario' as the default payment method for Boleto Bancario.") case boleto
```
## Screenshot of how it looks as Github comment
![image](https://github.com/user-attachments/assets/d069e9fc-9009-483c-bd0e-abd9ecf5e8a9)

# Proposed solution
Add newline break between annotation and case itself:

```swift
// From
case boleto

// To
@available(*, deprecated, renamed: "boletoBancarioSantander", message: "Use 'boletoBancarioSantander' instead. Consider 'boletoBancario' as the default payment method for Boleto Bancario.") 
case boleto
```

**Describe alternatives you've considered**
The only alternative at the moment is to pay 100% attention to the change set, follow and dissect every change.

**Comment by goergisn** [comment]
Hi, @atmamont 
thank you for the suggestion!

Here the PR that adds the functionality: https://github.com/Adyen/adyen-swift-public-api-diff/pull/70
